name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        deSfault: Hello
        required: true
        description: A cheerful word
jobs:
  run: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"